# Generated by Django 5.0.1 on 2024-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='join_players',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
