# Generated by Django 5.0.1 on 2024-01-29 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_result', to='game.game')),
                ('players', models.ManyToManyField(related_name='game_results', to='game.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='GameResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('participated_games', models.ManyToManyField(related_name='game_result_entries', to='game.gameresult')),
            ],
        ),
    ]
