# Generated by Django 5.0.1 on 2024-01-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameresult_gameresultentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
