# Generated by Django 5.0.2 on 2024-02-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameroom_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='subgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_games', to='game.game'),
        ),
    ]
