# Generated by Django 5.0.1 on 2024-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameplayer_user_alter_gameroom_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresultentry',
            name='participated_games',
        ),
        migrations.RemoveField(
            model_name='gameresultentry',
            name='intra_id',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='status',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='GameResultEntry',
        ),
    ]
