# Generated by Django 5.0.1 on 2024-02-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameplayer_user_alter_gameroom_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresultentry',
            name='participated_games',
        ),
        migrations.RemoveField(
            model_name='gameresultentry',
            name='intra_id',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='game.game'),
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='GameResultEntry',
        ),
    ]
