# Generated by Django 5.0.2 on 2024-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameplayer_rank_alter_subgame_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgame',
            name='t_end',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subgame',
            name='t_start',
            field=models.FloatField(default=0.0),
        ),
    ]
