# Generated by Django 5.0.3 on 2024-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_subgame_t_end_subgame_t_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='nickname',
            field=models.CharField(default='anonymous', max_length=32),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
