FROM python:3

# 작업 디렉토리 설정
WORKDIR /app

# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

# 의존성 파일 복사 및 설치
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# 프로젝트 파일 복사 및 실행 권한 부여
COPY . .
RUN chmod +x ./scripts/*.sh

# Django 애플리케이션 실행 명령
CMD ["./scripts/DEV_server_run.sh"]