# Generated by Django 5.0.2 on 2024-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socketcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketsession',
            name='game_room_session_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='socketsession',
            name='online_session_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
