# Generated by Django 5.0.1 on 2024-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avator',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='default.jpg', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
