# Generated by Django 5.0.1 on 2024-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_avator_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already taken.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'This nickname is already taken.'}, max_length=32, unique=True),
        ),
    ]
