# Generated by Django 5.0.1 on 2024-01-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_tournament', models.BooleanField(default=True)),
                ('game_point', models.PositiveIntegerField(default=1)),
                ('time_limt', models.PositiveIntegerField(default=180)),
                ('n_players', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_title', models.CharField(max_length=50)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('join_players', models.PositiveIntegerField(default=1)),
                ('game_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_room', to='game.game')),
            ],
        ),
    ]
