# Generated by Django 5.0.1 on 2024-01-18 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_tournament', models.BooleanField(default=True)),
                ('game_point', models.PositiveIntegerField(default=1)),
                ('time_limit', models.PositiveIntegerField(default=180)),
                ('n_players', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('join_players', models.PositiveIntegerField(default=0)),
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_room', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(default='anonymous', max_length=50)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='game.game')),
                ('intra_id', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game_id', 'intra_id')},
            },
        ),
    ]
