# Generated by Django 5.0.2 on 2024-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_twofactorauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='secret_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
