# Generated by Django 5.0.2 on 2024-02-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_twofactorauth_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='access_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='oauth',
            name='refresh_token',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
