# Generated by Django 5.0.3 on 2024-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_oauth_access_token_alter_oauth_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorauth',
            name='secret_code',
            field=models.CharField(null=True),
        ),
    ]
