# Generated by Django 5.0.3 on 2024-03-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_twofactorauth_secret_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauth",
            name="access_token",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="oauth",
            name="refresh_token",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="oauth",
            name="token_type",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="twofactorauth",
            name="secret_code",
            field=models.CharField(null=True),
        ),
    ]
